service: fiap-hackathon
frameworkVersion: '3'

package:
  patterns:
    - '!node_modules/.prisma/client/libquery_engine-*'
    - 'node_modules/.prisma/client/libquery_engine-rhel-*'
    - '!node_modules/prisma/libquery_engine-*'
    - '!node_modules/@prisma/engines/**'

provider:
  name: aws
  region: us-west-2
  runtime: nodejs20.x
  environment:
    DATABASE_URL: ${env:DATABASE_URL}
    AWS_COGNITO_CLIENT_ID: ${env:AWS_COGNITO_CLIENT_ID}
    AWS_COGNITO_CLIENT_SECRET: ${env:AWS_COGNITO_CLIENT_SECRET}
    AWS_SES_SOURCE: ${env:AWS_SES_SOURCE}
  tags:
    PROJECT: fiap-hackathon
  iamRoleStatements:
    - Effect: Allow
      Action:
        - "ses:SendEmail"
        - "ses:SendRawEmail"
      Resource: "*"

functions:
  api:
    handler: dist/main/lambda.api
    events:
      - httpApi:
          method: 'ANY'
          path: '/{proxy+}'
  
plugins:
  - serverless-offline